### ISSUE TITLE
Broken Image tags

### ISSUE THREAD

**Issue by rishi11** [yogimiraje/CS5610-yogi#1]
In your experiments you have used image tags but source of those tag is not correct. Please fix them.

**Comment by yogimiraje** [comment]
Tried to include the functionality inside function(), but did not work. Have talked to Rishi, working on the problem.

**Comment by yogimiraje** [comment]
This is proxy server error. The image is retrieved properly. I have checked it in console. Also,  first time it may not work however for next attempt it displays it correctly. Closing as  logistic issue.
