### ISSUE TITLE
Week 6 : Experiments Missing

### ISSUE THREAD

**Issue by rishi11** [yogimiraje/CS5610-yogi#2]
Please complete 5 experiments for this week.

**Comment by yogimiraje** [comment]
I have pushed week 6 changes already.  

As I discussed with you, for week 6 , I have done a single petition filing application which comprised of 5 experiments. The details are in the link below: 
http://net4.ccs.neu.edu/home/yogi/story/index.htm?../experiments/week6/story.txt

Can you please let me know if you are looking for something else.

**Comment by rishi11** [comment]
If it is huge experiment, Split the experiment into 5 small experiments (May be in single file or in 5 separate files). Document this experiments so that it will be considered as 5 experiments.

**Comment by yogimiraje** [comment]
Experiment split completed as requested.
