### ISSUE TITLE
Week 7 : Experiments Missing

### ISSUE THREAD

**Issue by rishi11** [yogimiraje/CS5610-yogi#3]
Please complete 5 experiments for this week.

**Comment by yogimiraje** [comment]
I am facing some issues in hosting them onto openshift and hopefully, it will be resolved by tonight.

**Comment by yogimiraje** [comment]
I was able to host my application on openshift after struggling a lot. Now, I have not pushed all my changes.

**Comment by rishi11** [comment]
There are only 3 experiments for Week 5. Please complete

**Comment by yogimiraje** [comment]
Experiment split completed as requested.
